name: learn-github-actions
on:
  push:
    paths:
      - 'doc/**'

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mkrakowitzer/actions-makepdfs@master
        with:
          markdown_dir: doc
          output_dir: tmp
      - uses: actions/upload-artifact@v2
        with:
          name: test-pdfs
          path: tmp
